# Generated by Django 3.1.6 on 2021-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bs_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=200)),
                ('publishedDate', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=12)),
                ('previewlink', models.CharField(max_length=200)),
                ('itemid', models.CharField(max_length=100)),
            ],
        ),
    ]
