# Generated by Django 3.1.6 on 2021-02-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bs_app',
            new_name='BS_tab',
        ),
    ]
